# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-31 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oneplus5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('title_desc', models.CharField(max_length=200)),
                ('img_url', models.ImageField(upload_to=b'uploads/')),
            ],
            options={
                'verbose_name': 'OnePlus5',
                'verbose_name_plural': 'OnePlus5',
            },
        ),
        migrations.CreateModel(
            name='OnePlusNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u914d\u7f6e\u4ecb\u7ecd')),
                ('index', models.IntegerField(default=999, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': 'oneplus\u914d\u7f6e',
                'verbose_name_plural': 'oneplus\u914d\u7f6e',
            },
        ),
    ]
