# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170731_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x90\x8d\xe5\xad\x97')),
                ('phone', models.CharField(max_length=500, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('img2_url', models.ImageField(upload_to=b'uploads/', verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x9b\xbe\xe7\x89\x872')),
                ('content', models.TextField(verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87\xe4\xb8\x8b\xe8\xbd\xbd')),
                ('ProPic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ProPic', verbose_name=b'\xe7\xb3\xbb\xe5\x88\x97')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u56fe\u72472',
                'verbose_name_plural': '\u4ea7\u54c1\u56fe\u72472',
            },
        ),
    ]
