# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-04 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_picture2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x90\x8d\xe5\xad\x97')),
                ('img2_url', models.ImageField(upload_to=b'uploads/blog/Picture_detail', verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x9b\xbe\xe7\x89\x872')),
                ('ProPic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ProPic', verbose_name=b'\xe7\xb3\xbb\xe5\x88\x97')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u56fe\u72472',
                'verbose_name_plural': '\u4ea7\u54c1\u56fe\u72472',
            },
        ),
        migrations.RemoveField(
            model_name='picture2',
            name='content',
        ),
        migrations.AlterField(
            model_name='picture2',
            name='img2_url',
            field=models.ImageField(upload_to=b'uploads/blog/Picture', verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x9b\xbe\xe7\x89\x872'),
        ),
    ]
