# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-31 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '\u5173\u4e8e\u4e00\u52a0',
                'verbose_name_plural': '\u5173\u4e8e\u4e00\u52a0',
            },
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img_url', models.ImageField(upload_to=b'uploads/')),
                ('img_desc', models.CharField(max_length=100)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('News', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.News')),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Video')),
            ],
            options={
                'verbose_name': '\u9996\u9875',
                'verbose_name_plural': '\u9996\u9875',
            },
        ),
        migrations.CreateModel(
            name='NavBars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NavName', models.CharField(max_length=10)),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6307\u5411\u5730\u5740')),
                ('english', models.CharField(blank=True, max_length=10)),
                ('NavLog', models.ImageField(blank=True, upload_to=b'uploads/')),
                ('NavImg', models.ImageField(blank=True, upload_to=b'uploads/')),
            ],
            options={
                'verbose_name': '\u5bfc\u822a',
                'verbose_name_plural': '\u5bfc\u822a',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '\u4e00\u52a0\u4ea7\u54c1',
                'verbose_name_plural': '\u4e00\u52a0\u4ea7\u54c1',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u652f\u6301',
                'verbose_name_plural': '\u670d\u52a1\u652f\u6301',
            },
        ),
    ]
