# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-01 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u641c\u7d22\u5185\u5bb9',
                'verbose_name_plural': '\u641c\u7d22\u5185\u5bb9',
            },
        ),
    ]
