# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-01 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='color',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='product_details',
            name='color_img',
            field=models.ImageField(blank=True, upload_to=b'shop/product/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='small_img',
            field=models.ImageField(blank=True, upload_to=b'shop/product/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product_desc',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product_desc',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='desc',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
    ]
