# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-01 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170801_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_details',
            options={'verbose_name': '\u5546\u54c1\u5c55\u793a', 'verbose_name_plural': '\u5546\u54c1\u5c55\u793a'},
        ),
    ]
