# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170801_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtags',
            name='TagImg',
            field=models.ImageField(blank=True, upload_to=b'shop/navtags/%Y/%m'),
        ),
    ]
