# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170803_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='navtags',
            name='style',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
