# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170803_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(max_length=10, upload_to=b'')),
                ('color_img', models.ImageField(blank=True, null=True, upload_to=b'shop/product/%Y/%m')),
                ('good', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.ShopSales')),
            ],
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='color_img',
        ),
    ]
