# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170803_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': '\u989c\u8272\u9009\u62e9', 'verbose_name_plural': '\u989c\u8272\u9009\u62e9'},
        ),
    ]
