# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170803_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
