# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-31 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '\u5e38\u89c1\u95ee\u9898',
                'verbose_name_plural': '\u5e38\u89c1\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('img_url', models.ImageField(upload_to=b'uploads/')),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u6211\u4eec',
                'verbose_name_plural': '\u8054\u7cfb\u6211\u4eec',
            },
        ),
        migrations.CreateModel(
            name='ServerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=b'uploads/', verbose_name='\u56fe\u7247')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u9009\u9879',
                'verbose_name_plural': '\u670d\u52a1\u9009\u9879',
            },
        ),
    ]
